version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
    depends_on:
      - db
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`unc.avoup.com`) || Host(`www.unc.avoup.com`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=leresolver"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"                    
      - "traefik.http.routers.laravel-secure.rule=Host(`unc.avoup.com`) || Host(`www.unc.avoup.com`)"  
      - "traefik.http.routers.laravel-secure.entrypoints=web"                                   
      - "traefik.http.routers.laravel-secure.middlewares=redirect-to-https"   

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - laravel_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.unc.avoup.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=leresolver"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"                    
      - "traefik.http.routers.phpmyadmin-secure.rule=Host(`pma.unc.avoup.com`)"  
      - "traefik.http.routers.phpmyadmin-secure.entrypoints=web"                                   
      - "traefik.http.routers.phpmyadmin-secure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.auth.basicauth.users=Gustaavolp:$$2y$$05$$dq4xoMGDwzOpZay90znzxOYVLfOCs9b6By4aG0ZaW4u9.y6gLBJni"  # Middleware de autenticacao
      - "traefik.http.routers.phpmyadmin.middlewares=auth"

volumes:
  db_data:

networks:
  laravel_network:
    external: true  # Garantir que a rede ja esteja criada externamente e conectada ao Traefik
